In [20]:
import pandas as pd
from collections import Counter

In [2]:
df = pd.read_csv('evaluation_table.csv')

In [6]:
df['side effect index (C)'].unique()

array([151714,  35344,   4144, ..., 154251,  14866,   9952])

In [10]:
df.shape

(924708, 10)

In [23]:
c = Counter(df[ (df['protein-based prediction']>0.5) & (df['drug-based prediction']<=0.5)]['side effect name'])
c.most_common(30)

[('Disorder Lung', 404),
 ('haemorrhoids', 384),
 ('angiopathy', 384),
 ('eruption', 382),
 ('insomnia', 350),
 ('bladder retention', 332),
 ('Hoarseness', 326),
 ('allergies', 318),
 ('aspiration pneumonia', 306),
 ('bundle branch block left', 302),
 ('abdominal pain upper', 296),
 ('wheeze', 294),
 ('hypoxia', 292),
 ('arterial pressure NOS increased', 292),
 ('arteriosclerosis', 288),
 ('haemorrhage rectum', 284),
 ('mucositis oral', 280),
 ('Embolism pulmonary', 272),
 ('alkalosis', 264),
 ('cellulitis', 262),
 ('Superficial thrombophlebitis', 262),
 ('hepatitis', 258),
 ('stridor', 256),
 ('Ataxia', 256),
 ('chronic obstructive airway disease', 248),
 ('myopia', 248),
 ('Amnesia', 248),
 ('blurred vision', 244),
 ('attempted suicide', 244),
 ('neumonia', 242)]

In [60]:
df_pp = df[ (df['protein-based prediction']>0.5) & (df['drug-based prediction']<=0.5)]
df_pp[ df_pp['side effect index (C)']==11991].sort_values('protein-based prediction', ascending=False)

side effect  side effect index (C) side effect name  drug1  \
234943          130                  11991         diarrhea    478   
234300          130                  11991         diarrhea    408   
233727          130                  11991         diarrhea     16   
234370          130                  11991         diarrhea    344   
234457          130                  11991         diarrhea    110   
...             ...                    ...              ...    ...   
233773          130                  11991         diarrhea     35   
234678          130                  11991         diarrhea    125   
234035          130                  11991         diarrhea    118   
234255          130                  11991         diarrhea    280   
234898          130                  11991         diarrhea    304   

        drug1 STITCH (CID)  drug2  drug2 STITCH (CID)  \
234943                2269    408                3478   
234300                3478    478                2269   
233727                5391    344                4634   
234370                4634     16                5391   
234457                2554     49             6398525   
...                    ...    ...                 ...   
233773                3911    113                3222   
234678                2405    118                2909   
234035                2909    125                2405   
234255                3367    304                5978   
234898                5978    280                3367   

        protein-based prediction  drug-based prediction  \
234943                  0.974980               0.406311   
234300                  0.974980               0.406311   
233727                  0.963967               0.459719   
234370                  0.963967               0.459719   
234457                  0.955052               0.500000   
...                          ...                    ...   
233773                  0.544548               0.500000   
234678                  0.541796               0.389320   
234035                  0.541796               0.389320   
234255                  0.530211               0.229956   
234898                  0.530211               0.229956   

        protein&drug-based prediction  
234943                       0.649343  
234300                       0.649343  
233727                       0.815752  
234370                       0.815752  
234457                       0.692992  
...                               ...  
233773                       0.703025  
234678                       0.596189  
234035                       0.596189  
234255                       0.592153  
234898                       0.592153  

[82 rows x 10 columns]

## GO

https://pypi.org/project/goatools/

https://www.ncbi.nlm.nih.gov/pubmed/27812946

https://nbviewer.jupyter.org/urls/dessimozlab.github.io/go-handbook/GO%20Tutorial%20in%20Python%20-%20Exercises.ipynb
https://nbviewer.jupyter.org/urls/dessimozlab.github.io/go-handbook/GO%20Tutorial%20in%20Python%20-%20Solutions.ipynb

In [35]:
import numpy as np
import scipy.sparse as sp

In [37]:
drug_protein = sp.load_npz('./data/sym_adj/drug-protein-sparse-adj.npz')

In [49]:
np.nonzero(drug_protein.toarray()[:, 9568])

(array([ 14,  31,  56,  97, 124, 127, 138, 237, 372, 379, 481, 493, 527,
        530, 615]),)

In [50]:
import pickle
with open('./data/index_map/protein-map.pkl', 'rb') as f:
    protein_map = pickle.load(f)

    # drug id - index
with open('./data/index_map/drug-map.pkl', 'rb') as f:
    drug_map = pickle.load(f)
inv_drug_map = {v: k for k, v in drug_map.items()}

# combo id - index
with open('./data/index_map/combo_map.pkl', 'rb') as f:
    combo_map = pickle.load(f)
inv_combo_map = {v: k for k, v in combo_map.items()}

with open('./data/index_map/combo-name-map.pkl', 'rb') as f:
    combo_name_map = pickle.load(f)
inv_combo_name_map = {v: k for k, v in combo_name_map.items()}

In [46]:
inv_protein_map = {v:k for k, v in protein_map.items()}

In [48]:
protein_map[1544]

9568

### Drug IDs interacting with this protein (9568 = gene ID)

In [54]:
[inv_drug_map[i] for i in np.nonzero(drug_protein.toarray()[:, 9568])[0].tolist()]

[4946,
 4917,
 3899,
 4485,
 271,
 4189,
 4543,
 4499,
 3767,
 3032,
 5472,
 3198,
 2099,
 3117,
 4932]

In [55]:
p_protein = sp.load_npz('./data/sym_adj/protein-sparse-adj.npz')

In [56]:
p_protein.toarray()

array([[0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# GO for human

## GO: protein

In [3]:
import Bio.UniProt.GOA as GOA

In [4]:
import os
from ftplib import FTP

data_folder = './data'
arab_uri = '/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz'
arab_fn = arab_uri.split('/')[-1]

# Check if the file exists already
arab_gaf = os.path.join(data_folder, arab_fn)
if(not os.path.isfile(arab_gaf)):
    # Login to FTP server
    ebi_ftp = FTP('ftp.ebi.ac.uk')
    ebi_ftp.login() # Logs in anonymously
    
    # Download
    with open(arab_gaf,'wb') as arab_fp:
        ebi_ftp.retrbinary('RETR {}'.format(arab_uri), arab_fp.write)
        
    # Logout from FTP server
    ebi_ftp.quit()
    
import gzip

# File is a gunzip file, so we need to open it in this way
with gzip.open(arab_gaf, 'rt') as arab_gaf_fp:
    arab_funcs = {}  # Initialise the dictionary of functions
    
    # Iterate on each function using Bio.UniProt.GOA library.
    for entry in GOA.gafiterator(arab_gaf_fp):
        uniprot_id = entry.pop('DB_Object_ID')
        arab_funcs[uniprot_id] = entry

In [14]:
protid = 'P05177'
protsym = 'CYP1A2' #CP1A2

In [15]:
[(ki,vi) for ki,vi in arab_funcs.items() if vi['DB_Object_Symbol']==protsym]

[('P05177',
  {'Annotation_Extension': '',
   'Aspect': 'F',
   'Assigned_By': 'UniProt',
   'DB': 'UniProtKB',
   'DB:Reference': ['PMID:12865317'],
   'DB_Object_Name': 'Cytochrome P450 1A2',
   'DB_Object_Symbol': 'CYP1A2',
   'DB_Object_Type': 'protein',
   'Date': '20190412',
   'Evidence': 'IDA',
   'GO_ID': 'GO:0101021',
   'Gene_Product_Form_ID': '',
   'Qualifier': [''],
   'Synonym': ['CYP1A2'],
   'Taxon_ID': ['taxon:9606'],
   'With': ['']})]

In [16]:
[(ki,vi) for ki,vi in arab_funcs.items() if ki==protid]

[('P05177',
  {'Annotation_Extension': '',
   'Aspect': 'F',
   'Assigned_By': 'UniProt',
   'DB': 'UniProtKB',
   'DB:Reference': ['PMID:12865317'],
   'DB_Object_Name': 'Cytochrome P450 1A2',
   'DB_Object_Symbol': 'CYP1A2',
   'DB_Object_Type': 'protein',
   'Date': '20190412',
   'Evidence': 'IDA',
   'GO_ID': 'GO:0101021',
   'Gene_Product_Form_ID': '',
   'Qualifier': [''],
   'Synonym': ['CYP1A2'],
   'Taxon_ID': ['taxon:9606'],
   'With': ['']})]

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P05177

## GO: all

In [20]:
import wget,os

go_obo_url = 'http://purl.obolibrary.org/obo/go/go-basic.obo'
data_folder = os.getcwd() + '/data'

# Check if we have the ./data directory already
if(not os.path.isfile(data_folder)):
    # Emulate mkdir -p (no error if folder exists)
    try:
        os.mkdir(data_folder)
    except OSError as e:
        if(e.errno != 17):
            raise e
else:
    raise Exception('Data path (' + data_folder + ') exists as a file. '
                   'Please rename, remove or change the desired location of the data path.')

# Check if the file exists already
if(not os.path.isfile(data_folder+'/go-basic.obo')):
    go_obo = wget.download(go_obo_url, data_folder+'/go-basic.obo')
else:
    go_obo = data_folder+'/go-basic.obo'

In [23]:
# Import the OBO parser from GOATools
from goatools import obo_parser

go = obo_parser.GODag(go_obo)

/mnt/c/Users/laure/Documents/git/TIP/data/go-basic.obo: fmt(1.2) rel(2019-12-09) 47,311 GO Terms


In [38]:
kk = go[list(go.keys())[0]]
kk.namespace

'biological_process'

In [ ]:
processes = {k:v for k,v in go.items() if v.namespace=='biological_process'}

### For each process, get the set of proteins (genes)

In [42]:
# processes

## Utility/significance of explaining
- know mechanism, can predict triple/higher-order side effects
    - other drugs affecting the same (GO) processes
- help design new polypharmacy treatment to counter the side effect

## Software availability
- module
- Biopython accesses our module's API (contribute to Biopython)
